# Generated by Django 4.2 on 2023-04-21 10:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WorkoutMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="Workout Name")),
                (
                    "workout_type",
                    models.CharField(
                        choices=[("WEIGHT LIFTING", "WEIGHTS"), ("CARDIO", "CARDIO")],
                        default="WEIGHTS",
                        max_length=256,
                        verbose_name="Workout Type",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="WeightedWorkoutLogMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_time",
                    models.DateTimeField(
                        default=datetime.datetime.now, verbose_name="Workout Date"
                    ),
                ),
                ("sets", models.PositiveIntegerField(verbose_name="Workout Sets")),
                (
                    "repetition",
                    models.PositiveIntegerField(verbose_name="Workout Repetitions"),
                ),
                (
                    "weight",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Weight Lifted"
                    ),
                ),
                (
                    "weight_metric",
                    models.CharField(
                        blank=True,
                        choices=[("Kilo Grams", "KG"), ("Pounds", "LBS")],
                        max_length=256,
                        null=True,
                        verbose_name="Weight Metric",
                    ),
                ),
                (
                    "calories",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="Calories Burned",
                    ),
                ),
                (
                    "workout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workout.workoutmaster",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProgramMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="Program Name")),
                (
                    "start_date",
                    models.DateField(
                        default=datetime.datetime.now, verbose_name="Program Start Date"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Program End Date"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workouts",
                    models.ManyToManyField(
                        related_name="workouts", to="workout.workoutmaster"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProgramLogMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_time",
                    models.DateTimeField(
                        default=datetime.datetime.now, verbose_name="Program Date"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workout.programmaster",
                    ),
                ),
            ],
        ),
    ]
