# Generated by Django 4.2 on 2023-04-21 11:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workout", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="programmaster",
            name="workouts",
            field=models.ManyToManyField(
                related_name="program_workouts", to="workout.workoutmaster"
            ),
        ),
    ]
