# Generated by Django 4.2 on 2023-05-01 13:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("workout", "0002_alter_programmaster_workouts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workoutmaster",
            name="workout_type",
            field=models.CharField(
                choices=[("WEIGHT LIFTING", "WEIGHT LIFTING"), ("CARDIO", "CARDIO")],
                default="WEIGHT LIFTING",
                max_length=256,
                verbose_name="Workout Type",
            ),
        ),
        migrations.CreateModel(
            name="CardioWorkoutLogMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_time",
                    models.DateTimeField(
                        default=datetime.datetime.now, verbose_name="Cardio Date"
                    ),
                ),
                ("laps", models.PositiveIntegerField(verbose_name="Cardio Laps")),
                (
                    "distance",
                    models.PositiveBigIntegerField(
                        verbose_name="Distance Covered (Km)"
                    ),
                ),
                (
                    "calories",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="Calories Burned",
                    ),
                ),
                (
                    "workout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workout.workoutmaster",
                    ),
                ),
            ],
        ),
    ]
